using System.Collections.Generic;
using System.Linq;

namespace ProjectEuler.EulerProblems
{
    public class EulerProblem2 : IEulerProblem
    {
        private readonly int _result;

        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        ///1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        ///By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        /// </summary>
        public EulerProblem2()
        {
            var fibSequence = new List<int> { 1, 2 };

            while (fibSequence.Max() <= 4000000)
            {
                var fibSequenceDesc = fibSequence.OrderByDescending(x => x).Take(2).Sum();
                fibSequence.Add(fibSequenceDesc);
            }

            _result = fibSequence.Where(x => x%2 == 0).Sum();
        }

        public string Solution
        {
            get { return _result.ToString(); }
        }
    }
}
